# Generated by Django 3.2.6 on 2021-09-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0003_auto_20210907_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='price',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=10),
        ),
        migrations.AddField(
            model_name='beat',
            name='stock',
            field=models.IntegerField(null=True),
        ),
    ]
